### ISSUE TITLE
Add yearly email verification, for quitting students

### ISSUE THREAD

**Issue by LucasPlacentino** [bepolytech/ULBDiscordBot#14]
check every year in, like, early November or late October, each student's email to make sure they are still registered at ULB. If not, delete them from the database

**Comment by OscarVsp** [comment]
No way to automatically check the validity of an ulb email address.

Only way to do this is to remove every registered user and ask them to register again (which can easily be done with a discord cmd)

**Comment by OscarVsp** [comment]
Admin can now user /yearly-update to remove all users from the database and send them a message to tell them the reason and ask them to register again with #15
